PACKAGE_NAME="membuf"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="membuf"
BUILRT_MODULE_LOCATION[0]="."

DEST_MODULE_LOCATION[0]="/kernel/drivers/char"

MAKE[0]="make all"
CLEAN="make clean"

AUTOINSTALL="yes"
